/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample1;

//import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import com.google.gson.JsonParser;

@TestInstance(LifeCycle.PER_CLASS)
class AppTest {
    private static final String baseUrl = "https://u57nfat2zh.execute-api.ap-northeast-1.amazonaws.com/prod/v1/";
    private ApiTester apiTester = new ApiTester(baseUrl);

    @ParameterizedTest
    @ExcelSource(file = "../testdata/test1.xlsx", sheet = "Sheet1")
    void test1(TestData testData) throws Exception {
        apiTester.TestApi(testData);
    }

    //@Test
    @ParameterizedTest
    @ValueSource(strings = { "/resource/${result1.id} aaa ${result1.id} bbb ${result1.obj1} ccc", "{\"id\":\"${result1.id}\"}", "{\"obj1\":${result1.obj1}}" })
    void test2(String s) throws Exception {
        String resultJson = "{\"id\":\"abcd1234\",\"obj1\":{\"item1\":\"value1\",\"item2\":\"value2\"}}";
        apiTester.addResult("result1", JsonParser.parseString(resultJson));
        String json = apiTester.replaceParameter(s);
        System.out.println(json);
        //App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
