/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample1;

//import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test
    @ParameterizedTest
    @ExcelSource(file = "C:/Users/bosan/source/repos/excelSource/test1.xlsx", sheet = "Sheet1")
    void test1(TestData s) {
        System.out.println("input:" + s.getInput() + " expected:" + s.getExpected());
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    // @Test
    //@ParameterizedTest
    @ValueSource(strings = { "Java", "java", "JAVA" })
    void test2(String s) {
        System.out.println(s);
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
